(require '#:asdf)
(asdf:oos 'asdf:load-op '#:cl-glfw)
(asdf:oos 'asdf:load-op '#:cl-opengl)
(asdf:oos 'asdf:load-op '#:cl-glu)

(glfw:do-window (:title "A Simple cl-opengl Example")
    ((gl:matrix-mode :projection)
     (gl:load-identity)
     (unwind-protect (glu:perspective 45 4/3 0.1 50)
       (gl:matrix-mode :modelview)))
  (gl:clear :color-buffer-bit)
  (gl:load-identity)
  (gl:translate 0 0 -5)
  (gl:rotate (* 10 (float (glfw:get-time) 0.0)) 1 1 0)
  (gl:rotate (* 90 (float (glfw:get-time) 0.0)) 0 0 1)
  (gl:begin :triangles)
  (gl:color 1 0 0) (gl:vertex  1  0 0)
  (gl:color 0 1 0) (gl:vertex -1  1 0)
  (gl:color 0 0 1) (gl:vertex -1 -1 0)
  (gl:end))
