(defpackage #:window
  (:use #:cl #:fuktard)
  (:export
   #:*scroll-x*
   #:*scroll-y*)
  (:export
   #:key-p
   #:key-j-p
   #:key-j-r)
  (:export
   #:get-proc-address
   #:init
   #:poll
   #:wrapper
   #:update-display
   #:set-vsync
   #:push-dimensions  
   #:set-caption)  
  (:export
   #:get-mouse-out
   #:get-mouse-position
   #:mice-locked-p
   #:mice-free-p
   #:toggle-mouse-capture)
  (:export
   #:*width*
   #:*height*
   #:*status*)
  (:export
   #:*resize-hook*))
