(require '#:asdf)
(asdf:oos 'asdf:load-op '#:cl-glfw)
(asdf:oos 'asdf:load-op '#:cl-glfw-opengl-version_1_1)
(asdf:oos 'asdf:load-op '#:cl-glfw-glu)
(asdf:oos 'asdf:load-op '#:cl-glfw-ftgl)

(let (font)
  (glfw:do-window (:title "FTGL Text example")
      ((gl:with-setup-projection
	 (glu:perspective 45 4/3 10 500))
       (setf font (ftgl:create-texture-font))
       (ftgl:set-font-face-size font 20 0))
    (gl:clear gl:+color-buffer-bit+)
    (gl:load-identity)
    (gl:translate-f 0 0 -400)
    (gl:rotate-f (* 10 (glfw:get-time)) 1 1 0)
    (gl:rotate-f (* 90 (glfw:get-time)) 0 0 1)
    (ftgl:render-font font "Hello world!" :all)))