(defpackage #:window
  (:use #:cl #:utility)
  (:export
   #:*scroll-x*
   #:*scroll-y*)
  (:export
   #:get-proc-address
   #:init
   #:poll
   #:wrapper
   #:update-display
   #:set-vsync
   #:push-dimensions  
   #:set-caption)  
  (:export
   #:get-mouse-out
   #:get-mouse-position
   #:mouse-locked?
   #:mouse-free?
   #:toggle-mouse-capture)
  (:export
   #:*width*
   #:*height*
   #:*status*)
  (:export
   #:*resize-hook*)
  (:export
   #:*mouse-x*
   #:*mouse-y*)
  (:export
   #:*control-state*
   #:*shift*
   #:*control*
   #:*alt*
   #:*super*)
  (:export
   ;;[FIXME]::This?
   #:update-control-state2
   #:update-control-state
   #:do-character-keys
   #:control-state-jp-or-repeat)
  (:export
   #:button))
